### PR TITLE
Fix to work in v3

### PR DESCRIPTION
**Pull request by daftspunk**
This fixes v3 + v2 compatibility. Not sure if it breaks v1. Perhaps a new major version is needed for this plugin

### CODE REVIEW

**Comment by daftspunk** [comment]
It might be a better idea to use an event inside `getAssetPath` instead of overriding this entire class.

**Comment by cydrickn** [comment]
Will test this first in v2 and v3.

**Comment by cydrickn** [comment]
Closes #11

**Comment by cydrickn** [comment]
This will be a major update,
With the test, this will break version 1.

**Review by cydrickn — APPROVED** [review]

**Pull request merged**
